import Head from "next/head";
import { ReactNode } from "react";
import Navigation from "./Navigation";

type PropType = {
  children: ReactNode;
};
export default function BookingLayout({ children }: PropType) {
  return (
    <>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white w-full">
        <Navigation/>
        <div className="">{children}</div>
      </main>
    </>
  );
}
