import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import Navigation from "./Navigation";
import Footer from "./Footer";
import Button from "./subcomponents/Button";
import { NextRouter, useRouter } from "next/router";
import Cookies from "js-cookie";
import jwtDecode from "jwt-decode";

type PropType = {
  children: ReactNode;
};
export default function Layout({ children }: PropType) {
  const router: NextRouter = useRouter();
  const [user, setUser] = useState();
  const token: any = Cookies.get("token");

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleClick = (e: any) => {
    e.preventDefault();
    router.push("Reservation");
  };

  useEffect(() => {
    if (token) setUser(jwtDecode(token));
  }, [token]);

  return (
    <>
      <Head>
        <title>GALTOGO APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-white min-h-screen sm:px-20">
        <Button
          className="fixed bottom-4 right-3 sm:right-20 lg:top-8 z-20"
          size="sm"
          onClick={handleClick}
        >
          + Reservation
        </Button>
        <Navigation user={user} setUser={setUser} />
        <div className="">{children}</div>
        <Footer />
      </main>
    </>
  );
}
