import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import { ReactNode } from "react";
import Side from "./Side";

type PropTypes = {
  children: ReactNode;
};

export default function Layout({ children }: PropTypes) {
  return (
    <>
      <Head>
        <title>GALTOGO Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-4">
        <Header />
        <div className="flex">
          <Side />
          {children}
        </div>
        <Footer />
      </main>
    </>
  );
}
