import Head from "next/head";
import Header from "./Header";
import { ReactNode } from "react";
import Sidebar from "./Sidebar";

type PropTypes = {
  children: ReactNode;
};

export default function Layout({ children }: PropTypes): JSX.Element {
  return (
    <>
      <Head>
        <title>GALTOGO Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Sidebar>
          <main className="bg-gray-100 min-h-screen">
            <Header />
            {children}
          </main>
        </Sidebar>
      </div>
    </>
  );
}
